"""
Script untuk update Gemini API Key dengan mudah
Usage: python update_api_key.py [API_KEY]
"""

import os
import sys
from pathlib import Path

def update_api_key_in_env(api_key: str):
    """Update API key di file .env"""
    env_path = Path(__file__).parent / '.env'
    
    # Baca file .env jika ada
    env_vars = {}
    if env_path.exists():
        with open(env_path, 'r', encoding='utf-8') as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith('#') and '=' in line:
                    key, value = line.split('=', 1)
                    env_vars[key.strip()] = value.strip()
    
    # Update atau tambahkan GEMINI_API_KEY
    env_vars['GEMINI_API_KEY'] = api_key
    
    # Tulis kembali ke file .env
    with open(env_path, 'w', encoding='utf-8') as f:
        f.write("# Environment Variables untuk Temanikan Backend\n")
        f.write("# Auto-generated by update_api_key.py\n\n")
        f.write(f"GEMINI_API_KEY={api_key}\n")
        
        # Tulis variabel lain yang sudah ada
        for key, value in env_vars.items():
            if key != 'GEMINI_API_KEY':
                f.write(f"{key}={value}\n")
    
    print(f"✅ API Key berhasil diupdate di {env_path}")
    return True

def update_api_key_in_config(api_key: str):
    """Update API key di config.py sebagai fallback"""
    config_path = Path(__file__).parent / 'config.py'
    
    with open(config_path, 'r', encoding='utf-8') as f:
        content = f.read()
    
    # Ganti nilai default di config.py
    import re
    pattern = r"GEMINI_API_KEY = os\.getenv\('GEMINI_API_KEY', '[^']+'\)"
    replacement = f"GEMINI_API_KEY = os.getenv('GEMINI_API_KEY', '{api_key}')"
    
    new_content = re.sub(pattern, replacement, content)
    
    with open(config_path, 'w', encoding='utf-8') as f:
        f.write(new_content)
    
    print(f"✅ API Key berhasil diupdate di {config_path} (fallback)")
    return True

def main():
    if len(sys.argv) < 2:
        print("=" * 70)
        print("🔑 Update Gemini API Key")
        print("=" * 70)
        print("\nUsage:")
        print("  python update_api_key.py [API_KEY]")
        print("\nContoh:")
        print("  python update_api_key.py AIzaSyA_nyNIO60t4OUKkJLKgPnXw4EwoUcOfB8")
        print("\nAtau masukkan API key secara interaktif:")
        api_key = input("\nMasukkan API Key baru: ").strip()
        if not api_key:
            print("❌ API Key tidak boleh kosong!")
            sys.exit(1)
    else:
        api_key = sys.argv[1].strip()
    
    if not api_key:
        print("❌ API Key tidak boleh kosong!")
        sys.exit(1)
    
    if not api_key.startswith('AIza'):
        print("⚠️  Warning: API Key biasanya dimulai dengan 'AIza'")
        response = input("Lanjutkan? (y/n): ").strip().lower()
        if response != 'y':
            print("❌ Dibatalkan")
            sys.exit(1)
    
    print("\n🔄 Mengupdate API Key...")
    
    # Update di .env (prioritas utama)
    try:
        update_api_key_in_env(api_key)
    except Exception as e:
        print(f"⚠️  Warning: Gagal update .env: {e}")
    
    # Update di config.py sebagai fallback
    try:
        update_api_key_in_config(api_key)
    except Exception as e:
        print(f"❌ Error: Gagal update config.py: {e}")
        sys.exit(1)
    
    print("\n" + "=" * 70)
    print("✅ API Key berhasil diupdate!")
    print("=" * 70)
    print("\n📋 Langkah selanjutnya:")
    print("1. Restart backend server agar perubahan diterapkan")
    print("2. Test AI chat untuk memastikan berfungsi")
    print("3. Cek log backend jika ada error")
    print("\n💡 Tips:")
    print("- API key disimpan di file .env (prioritas)")
    print("- Jika .env tidak ada, akan menggunakan config.py")
    print("- Pastikan file .env tidak di-commit ke Git!")

if __name__ == '__main__':
    main()



